force-app/main/default/objects/Account/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Client Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>New Lead</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Record type for Client</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <description>This field store&apos;s current location of the candidate.</description>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Birth__c</fullName>
    <description>This field stores date of birth of the candidate.</description>
    <label>Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Highest_Qualification__c.field-meta.xml
<CustomField>
    <fullName>Highest_Qualification__c</fullName>
    <inlineHelpText>Give comma separated values eg: B.Tech, M.Sc, M.Com, M.A, MBA</inlineHelpText>
    <label>Highest Qualification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsBillable__c.field-meta.xml
<CustomField>
    <fullName>IsBillable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field shows whether the candidate is billable(on project) or not.</description>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Experience__c.field-meta.xml
<CustomField>
    <fullName>Total_Experience__c</fullName>
    <description>Total number of years of professional experience the candidate has across all previous roles</description>
    <label>Total Experience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Candidate.recordType-meta.xml
<RecordType>
    <fullName>Candidate</fullName>
    <active>true</active>
    <description>Record type for Candidate</description>
    <label>Candidate</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Record type for Client</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Recruiter.recordType-meta.xml
<RecordType>
    <fullName>Recruiter</fullName>
    <active>true</active>
    <description>Record Type for Recruiter</description>
    <label>Recruiter</label>
</RecordType>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>IE-{0000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Candidate_Name__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Candidate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <description>Job roles opened by the client for hiring.</description>
    <label>Job Position</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Position__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Positions</relationshipLabel>
    <relationshipName>Job_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Will show that project is currently Active or not.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Actual_Cost__c.field-meta.xml
<CustomField>
    <fullName>Actual_Cost__c</fullName>
    <description>The actual monetary expenditure incurred on the project to date.</description>
    <label>Actual Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <description>The financial budget allocated for the entire project (typically in currency format).</description>
    <label>Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A brief summary of the project&apos;s scope, objectives, and business purpose.</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The planned or actual completion date of the project.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/No_of_employees__c.field-meta.xml
<CustomField>
    <fullName>No_of_employees__c</fullName>
    <description>The number of employees or resources assigned or planned for this project.</description>
    <inlineHelpText>Number of employees working on this project</inlineHelpText>
    <label>No of employees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The planned or actual start date of the project.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <description>This object save records of daily work entries.</description>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>It defines the project that you going to work on that</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{00000}</displayFormat>
        <label>WorkOrderID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Candidate_Name__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Candidate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The expected or actual end date of the candidate on the project.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the project they’re assigned to.</description>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Candidate_Project_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Recruiter_Name__c.field-meta.xml
<CustomField>
    <fullName>Recruiter_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recruiter Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Recruiter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Orders (Recruiter Name)</relationshipLabel>
    <relationshipName>Work_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Renewed__c.field-meta.xml
<CustomField>
    <fullName>Renewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Role_on_Project__c.field-meta.xml
<CustomField>
    <fullName>Role_on_Project__c</fullName>
    <description>Role played by the candidate (e.g., Developer, Analyst, Tester).</description>
    <label>Role on Project</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Salary_Offered__c.field-meta.xml
<CustomField>
    <fullName>Salary_Offered__c</fullName>
    <description>The compensation or rate agreed for the candidate on this specific assignment.</description>
    <label>Salary Offered</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The date the candidate joined or started on the project.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Assignment status: Assigned, On Hold, Released, Completed, etc.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Extended</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Onhold</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Recruitment_TestDataFactory.cls
/*
##################################################### 
# Created By (Date)   : Admin (22 Jul, 2025)
# Description         : This is a Data Factory class for test classes.
# Modifications Log   : 
* Ver    Date              Author         Modification
* 1.0    22 Jul, 2025      Admin          Initial Version
#####################################################
*/

@isTest
public class Recruitment_TestDataFactory {
    
/**
* @description  : Return a Candidate record with Name and Email.
* @param name   - Candidate name
* @param email  - Candidate email
* @return Candidate instance (not inserted)
*/
    public static Contact createCandidate(String name, String email) {
        // 1️⃣ Candidate Record Type Id fetch karo
    Id candidateRtId = Schema.SObjectType.Contact
        .getRecordTypeInfosByDeveloperName()
        .get('Candidate')
        .getRecordTypeId();
        system.debug('candidateRtId'+candidateRtId);
		Long ts = System.currentTimeMillis();
        return new Contact(
            LastName = name,
            Email = email,
            Date_of_Birth__c = Date.newInstance(1990, 1, 1),
            Phone = '99999' + Math.mod(ts, 100000),
            Current_Location__c = 'New York',
            Total_Experience__c = 5,
            Highest_Qualification__c = 'B.Tech',
            IsBillable__c=true,
            RecordTypeId = candidateRtId
            
        );
    }
    
/**
* @description  : Return a Project__c record with Description.
* @param description - Project description
* @return Project__c instance (not inserted)
*/
    public static Project__c createProject(String description) {
        return new Project__c(
            Description__c = description,
            Project_Name__c = 'test project',
            No_of_employees__c = 10,
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addDays(30),
            Budget__c = 50000,
            Actual_Cost__c = 20000,
            Active__c = true
        );
    }
    
/**
* @description  : Return a Recruiter record with Name and Email.
* @param name   - Recruiter name
* @param email  - Recruiter email
* @return Recruiter instance (not inserted)
*/
    public static Contact createRecruiter(String lastName, String email) {
		Id recruiterRtId = Schema.SObjectType.Contact
        .getRecordTypeInfosByDeveloperName()
        .get('Recruiter')
        .getRecordTypeId();
        return new Contact(
            LastName = lastName,
            Email = email,
            Phone = '9000000000',
			RecordTypeId = recruiterRtId
        );
    }
    
/**
* @description  : Return a Work_Order__c record with related Candidate, Project, and Recruiter.
* @param Id   - candidate Id
* @param Id   - project Id
* @param Id   - recruiter Id
* @return Work_Order__c instance (not inserted)
*/
    
    public static Work_Order__c createWorkOrder(Id candidateId, Id projectId, Id recruiterId) {
        return new Work_Order__c(
            Candidate_Name__c = candidateId,
            Project__c = projectId,
            Role_on_Project__c = 'Developer', 
            Recruiter_Name__c = recruiterId,
            Renewed__c = false,
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addMonths(6),
            Status__c = 'Working', 
            Salary_Offered__c = 50000
        );
    }
    
/**
* @author (date): Admin (20 Aug, 2025)
* @description  : Return a Client record with sample data.
* @param name: Name for Client.
* @param email: Email for Client.
* @return Client instance (not inserted).
*/
    public static Account createClient(String name, String email) {
        
        // 1️⃣ Client Record Type Id fetch karo
        Id clientRtId = Schema.SObjectType.Account
            .getRecordTypeInfosByDeveloperName()
            .get('Client')
            .getRecordTypeId();
        // 2️⃣ Account record create karo
        Account acc = new Account(
            Name = name,
            Phone = '9999999999',
            Email__c = email,        // agar Person Account hai
            IsActive__c = true,         // custom field
            RecordTypeId = clientRtId
        );
        
        return acc;
    }
    
/**
* @author (date): Admin (20 Aug, 2025)
* @description  : Return a Job_Position__c record with sample data.
* @param client   - Related Client record (required).
* @param Project  - Related Project__c record (required).
* @return Job_Position__c instance (not inserted).
*/
    public static Job_Position__c createJobPosition(Account client, Project__c proj) {
        return new Job_Position__c(
            Job_Title__c = 'Salesforce Developer',
            Client_Name__c = client.Id,
            Employment_Type__c = 'Full-Time',
            Skills_Required__c = 'Salesforce Developer',
            Project__c = proj.Id
       
        );
    }
    
/**
* @author (date): Admin (20 Aug, 2025)
* @description  : Return an Interview__c record with sample data.
* @param candidate - Related Candidate record (required).
* @param jobPos    - Related Job_Position__c record (required).
* @return Interview__c instance (not inserted).
*/
    public static Interview__c createInterview(Contact candidate, Job_Position__c jobPos) {
        return new Interview__c(
            Candidate_Name__c = candidate.Id,
            Job_Position__c = jobPos.Id,                   
            Interview_Status__c = 'New',
            Feedback__c = 'The candidate demonstrated a clear understanding of the role and articulated their past experience in a structured and coherent manner. They were able to explain core concepts relevant to the position and provided practical examples from previous projects, indicating hands-on exposure. Communication was generally effective, with responses that were relevant and appropriately detailed, although some answers could benefit from deeper technical or analytical elaboration.'
        );
    }
    
/**
* @author (date): Admin (20 Aug, 2025)
* @description  : Return an Interview__c record with sample data.
* @param candidate - Related Candidate record (required).
* @param jobPos    - Related Job_Position__c record (required).
* @return Interview__c instance (not inserted).
*/
    public static Interview__c createInterviewWithoutRound(Contact candidate, Job_Position__c jobPos) {
        return new Interview__c(
            Candidate_Name__c = candidate.Id,
            Job_Position__c = jobPos.Id,                    
            Interview_Status__c = 'New',
            Feedback__c = 'Initial feedback'
        );
    }

/** 
* @author (date): Admin (20 Aug, 2025)
* @description  : Return an Client record with sample data.
* @param candidate - Related Candidate record (required).
* @param jobPos    - Related Job_Position__c record (required).
* @return Client instance.
*/
    public static Account createFlexClient(String name, String email) {
        Id candidateRecordTypeId;
            try {
                candidateRecordTypeId = [
                    SELECT Id 
                    FROM RecordType 
                    WHERE SObjectType = 'Account' 
                    AND Name = 'Client' 
                    LIMIT 1
                ].Id;
            } catch (Exception e) {
                throw new AuraHandledException('Candidate Record Type not found for Contact');
            }
        return new Account(
            Name = name,
            Phone__c = '9999999999',
            Email__c = email,
            isActive__c = true,
            RecordtypeId = candidateRecordTypeId
        );
    }
 
/* @author (date): Admin (20 Aug, 2025)
* @description  : Return an Job_Position__c record with sample data.
* @return Job_Position__c instance.
*/     
    public static Job_Position__c createFlexJobPosition() {
        return new Job_Position__c(
            Job_Title__c = 'Salesforce Developer',        
            Employment_Type__c = 'Full-Time',
            Skills_Required__c = 'Salesforce, Admin',       
            Status__c = 'Open'          
        );
    }
      public static CustomSetting__c getValidationBypassSetting() {
        CustomSetting__c cs = CustomSetting__c.getOrgDefaults();
        if (cs == null) {
            cs = new CustomSetting__c(
                SetupOwnerId = UserInfo.getOrganizationId()
            );
        }
        return cs;
    }
    
    
     /**
     * @author (date): Admin (9 september, 2025)
     * @description  : Returns an Event record with sample data related to the given Candidate.
     * @param candidate - Related Candidate record (required).
     * @return Event instance.
     */
    
    public static Event createEvent(Contact candidate,Job_Position__c job) {
        return new Event(
            Subject = 'Team Meeting',
            StartDateTime = System.now().addDays(1),
            EndDateTime = System.now().addDays(1).addHours(1),
            	WhatId=job.id,
          
            DurationInMinutes = 60,
          	 WhoId = candidate.Id,
            Location = 'Conference Room',
            Description = 'Discussion about project status'
        );
    }

    /**
    * @description  : Create a Timesheet__c instance and Return.
    * @param Id   - name String
    * @return Timesheet__c instance (not inserted)
    */
	public static Timesheet__c createTimesheet(String name) {
          Timesheet__c ts = new Timesheet__c( Date__c = Date.today());
            return ts;
    }
}