force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>New Lead</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Project Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Identifies the Task Type associated with this Project. The selected Task Type determines the applicable billable rate when the Project uses the Time &amp; Materials billing model with Rate Type set to Task Billable Rate.</description>
    <inlineHelpText>Select the Task Type whose predefined billable rate should be applied to this project when Task Billable Rate is selected as the Rate Type.</inlineHelpText>
    <label>Task Type</label>
    <referenceTo>Task_Type__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task_Type__c/Task_Type__c.object-meta.xml
<CustomObject>
    <label>Task Type</label>
    <nameField>
        <label>Task Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Type__c/fields/Billable_Non_Billable__c.field-meta.xml
<CustomField>
    <fullName>Billable_Non_Billable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Billable ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Task_Type__c/fields/Billing_rate_per_hour__c.field-meta.xml
<CustomField>
    <fullName>Billing_rate_per_hour__c</fullName>
    <label>Billing rate (per hour)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Task_Type__c/fields/Task_Type_Project__c.field-meta.xml
<CustomField>
    <fullName>Task_Type_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Type Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Task Types</relationshipLabel>
    <relationshipName>Task_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <description>Captures number of hours worked on that date (e.g., 8.0, 4.5).</description>
    <label>Hours</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Associates the time entry with a specific project. Used for reporting and billing reference.</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Identifies who performed the work. Should match the Resource on Timesheet.</description>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Reflects status inherited from Timesheet or controlled via process.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Type</label>
    <referenceTo>Task_Type__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Timesheet__c</fullName>
    <description>Links time entry to a specific Timesheet. Defines week-wise grouping of entries. Enables roll-up of total hours.</description>
    <label>Timesheet</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Work_Date__c.field-meta.xml
<CustomField>
    <fullName>Work_Date__c</fullName>
    <description>Specifies the exact date when the work was performed. Must fall within Timesheet week range.</description>
    <label>Work Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <description>This object save records of daily work entries.</description>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>It defines the project that you going to work on that</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Identifies the employee who logged the time. Used for approval routing and reporting.</description>
    <inlineHelpText>It tells about the candidate of the timesheet</inlineHelpText>
    <label>Resource</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Week_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_End_Date__c</fullName>
    <description>Defines the ending date of the reporting week. Used for validation and reporting.</description>
    <inlineHelpText>It defines the deadline of the of the end week</inlineHelpText>
    <label>Week End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Week_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Week_Start_Date__c</fullName>
    <description>Defines the starting date of the reporting week. Prevents duplicate weekly entries.</description>
    <inlineHelpText>It defines the starting week date of the timesheet</inlineHelpText>
    <label>Week Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BillableNonBillableTaskTypeTest.cls
/*
#####################################################
# @Created By (Date)   : Kshitiz (12 Mar, 2026)
# @Description         : Apex Test Class for BillableNonBillableTaskTypeController
#                       - Validates retrieval of Task Types for a Project.
# @Modifications Log   :
# Ver    Date              Author                 Modification
# 1.0    12 March, 2026    Kshitiz                Initial Version
#####################################################
*/
@IsTest
public class BillableNonBillableTaskTypeTest {

    /*
     * @description : @testSetup method used to create reusable test data
     *                shared across all test methods.
     **/
    @TestSetup
    static void setupData() {

        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];

        User u = new User(
            FirstName = 'Test',
            LastName = 'Owner',
            Alias = 'tuser',
            Email = 'testuser@example.com',
            Username = 'testuser' + System.currentTimeMillis() + '@example.com',
            CommunityNickname = 'testuser' + System.currentTimeMillis(),
            ProfileId = p.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_IN',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert u;

        // Project
        Project__c project =
            Recruitment_TestDataFactory.createProject('Test Project');
        insert project;

        // Account + Resource
        Account acc = new Account(Name='Test Account');
        insert acc;

        Contact resource = new Contact(
            LastName = 'Resource User',
            AccountId = acc.Id
        );
        insert resource;

        Date today = Date.today();
        Date weekStart = today.toStartOfWeek().addDays(1);
        Date weekEnd = weekStart.addDays(6);

        // Timesheet
        Timesheet__c ts = Recruitment_TestDataFactory.createTimesheet('test');
        ts.Project__c = project.Id;
        ts.Resource__c = resource.Id;
        ts.Status__c = 'Draft';
        ts.Week_Start_Date__c = weekStart;
        ts.Week_End_Date__c = weekEnd;
        insert ts;

        // Task Type
        Task_Type__c taskType = new Task_Type__c(
            Name = 'Development',
            Task_Type_Project__c = project.Id,
            Billable_Non_Billable__c = true,
            Billing_rate_per_hour__c = 100
        );
        insert taskType;

        // Existing Time Entries
        List<Time_Entry__c> entries = new List<Time_Entry__c>();

        for(Integer i = 0; i < 3; i++){

            Time_Entry__c te = new Time_Entry__c(
                Timesheet__c = ts.Id,
                Task_Type__c = taskType.Id,
                Hours__c = 4,
                Resource__c = resource.Id,
                Project__c = project.Id,
                Work_Date__c = weekStart.addDays(i)
            );

            entries.add(te);
        }

        insert entries;
    }


    /**
      * @description : Tests retrieval of Task Types associated
 	  *                with a given Project Id.
     */
    @IsTest
    static void testGetTaskTypes(){

        Project__c project = [SELECT Id FROM Project__c LIMIT 1];
        User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        System.runAs(u) {
        Test.startTest();

        List<Task_Type__c> taskTypes =
            BillableNonBillableTaskTypeController.getTaskTypes(project.Id);

        Test.stopTest();

        System.assert(!taskTypes.isEmpty(), 'Task types should be returned');
    }
    }

    /**
      * @description : Tests retrieval of existing Time Entry records
 	  *                for a Timesheet along with Timesheet status.
      */
    @IsTest
    static void testGetTimeEntries(){

        Timesheet__c ts = [SELECT Id FROM Timesheet__c LIMIT 1];
		User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        System.runAs(u) {
        Test.startTest();

        BillableNonBillableTaskTypeController.TimeEntryResponse response =
            BillableNonBillableTaskTypeController.getTimeEntries(ts.Id);

        Test.stopTest();

        System.assertEquals('Draft', response.timesheetStatus);
        System.assert(response.entries.size() > 0);
    }
    }

    /**
      * @description : Tests saving new Time Entry records through
 	  *                the controller using JSON wrapper input.
      **/
    @IsTest
    static void testSaveTimeEntries(){

        Timesheet__c ts = [SELECT Id FROM Timesheet__c LIMIT 1];
        Task_Type__c tt = [SELECT Id FROM Task_Type__c LIMIT 1];

        BillableNonBillableTaskTypeController.TimeEntryWrapper wrapper =
            new BillableNonBillableTaskTypeController.TimeEntryWrapper();

        wrapper.taskTypeId = tt.Id;
        wrapper.workDate = Date.today();
        wrapper.hours = 6;
        wrapper.note = 'Worked on module';

        List<BillableNonBillableTaskTypeController.TimeEntryWrapper> listWrap =
            new List<BillableNonBillableTaskTypeController.TimeEntryWrapper>{wrapper};

        String jsonInput = JSON.serialize(listWrap);
		User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        System.runAs(u) {
        Test.startTest();

        BillableNonBillableTaskTypeController.saveTimeEntries(
            ts.Id,
            jsonInput,
            'Draft'
        );

        Test.stopTest();

        List<Time_Entry__c> entries =
            [SELECT Id FROM Time_Entry__c WHERE Timesheet__c = :ts.Id];

        System.assert(entries.size() > 0);
    }
    }

    /**
     * @description : Tests updating existing Time Entry records.
     */
    @IsTest
    static void testUpdateTimeEntries(){

        Time_Entry__c entry =
            [SELECT Id, Hours__c, Timesheet__c FROM Time_Entry__c LIMIT 1];

        entry.Hours__c = 7;
		User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        System.runAs(u) {
        Test.startTest();

        BillableNonBillableTaskTypeController.updateTimeEntries(
            new List<Time_Entry__c>{entry}
        );

        Test.stopTest();

        Time_Entry__c updated =
            [SELECT Hours__c FROM Time_Entry__c WHERE Id = :entry.Id];

        System.assertEquals(7, updated.Hours__c);
    }
    }

    /**
     * @description : Tests successful update of Timesheet status.
     */
    @IsTest
    static void testUpdateTimesheet(){

        Timesheet__c ts = [SELECT Id, Status__c FROM Timesheet__c LIMIT 1];

        ts.Status__c = 'Submitted';
		User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
        System.runAs(u) {
        Test.startTest();

        BillableNonBillableTaskTypeController.updateTimesheet(ts);

        Test.stopTest();

        Timesheet__c updated =
            [SELECT Status__c FROM Timesheet__c WHERE Id = :ts.Id];

        System.assertEquals('Submitted', updated.Status__c);
    }
    }

    /**
      * @description : Tests validation scenario where a Submitted
 	  *                Timesheet is attempted to be reverted back
 	  *                to Draft status.
      */
    @IsTest
    static void testUpdateTimesheetException(){

        Timesheet__c ts = [SELECT Id, Status__c FROM Timesheet__c LIMIT 1];

        ts.Status__c = 'Submitted';
        update ts;

        Boolean exceptionThrown = false;

        try{

            ts.Status__c = 'Draft';
			User u = [SELECT Id FROM User WHERE Alias = 'tuser' LIMIT 1];
       		System.runAs(u) {
            Test.startTest();
            BillableNonBillableTaskTypeController.updateTimesheet(ts);
            Test.stopTest();
            }

        }catch(AuraHandledException e){
            exceptionThrown = true;
        }

        System.assert(exceptionThrown,
            'Exception should be thrown when downgrading Submitted timesheet');
    }
	
}