force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>IE-{0000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Candidate_Name__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Candidate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Position__c/Job_Position__c.object-meta.xml
<CustomObject>
    <description>Job roles opened by the client for hiring.</description>
    <label>Job Position</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Job ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InterviewServic.cls
public without sharing class InterviewServic {

    public static CandidatePublicController.CandidateResponse createInterview(
        Id candidateId,
        Id jobId
    ) {
        CandidatePublicController.CandidateResponse resp =
            new CandidatePublicController.CandidateResponse();

        try {
            if (candidateId == null || jobId == null) {
                resp.success = false;
                resp.message = 'CandidateId and JobId are required';
                return resp;
            }

            Interview__c interview = new Interview__c();
            interview.Candidate_Name__c = candidateId;
            interview.Job_Position__c = jobId;
           

            insert interview;

            resp.success = true;
            resp.message = 'Interview created successfully';
            resp.interviewCreated = true;
            resp.interviewId = interview.Id;

        } catch (Exception ex) {
            resp.success = false;
            resp.message = ex.getMessage();
            resp.interviewCreated = false;
        }

        return resp;
    }
}